services:
  - type: web
    name: autolux
    runtime: python
    plan: free
    disks:
      - name: media
        mountPath: /var/data
        sizeGB: 1
    buildCommand: ./build.sh
    startCommand: gunicorn autolux.wsgi:application --bind 0.0.0.0:$PORT
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.14.3
      - key: DJANGO_SETTINGS_MODULE
        value: autolux.settings
      - key: DEBUG
        value: "False"
      - key: MEDIA_ROOT
        value: /var/data/media
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
