# Generated by Django 6.0.1 on 2026-01-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_rename_task_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='year',
            new_name='Año',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='FuelType',
            new_name='Combustible',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='description',
            new_name='Descrepción',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='brand',
            new_name='Marca',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='carmodel',
            new_name='Modelo',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='engine',
            new_name='Motor',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='price',
            new_name='Precio',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='title',
            new_name='Titulo',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='transmission',
            new_name='Transmisión',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='availability',
            new_name='Vendido',
        ),
    ]
