# Generated by Django 6.0.1 on 2026-01-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_rename_year_stock_año_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Año',
            field=models.DateField(),
        ),
    ]
