# Generated by Django 6.0.1 on 2026-01-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_alter_stock_año'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Año',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
