# Generated by Django 6.0.1 on 2026-01-16 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0006_alter_stock_año'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Año',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
