# Generated by Django 6.0.1 on 2026-01-16 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0007_alter_stock_año'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='created_at',
            new_name='Fecha_de_creación',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='updated_at',
            new_name='Ultima_actualización',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='user',
            new_name='Usario',
        ),
    ]
