# Generated by Django 6.0.1 on 2026-01-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0008_rename_created_at_stock_fecha_de_creación_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='car_photos/'),
        ),
    ]
