# Generated by Django 6.0.1 on 2026-04-13 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0009_stock_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='Kilometros',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
