# Generated by Django 6.0.1 on 2026-04-13 22:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0010_stock_kilometros'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='Matricula',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='VIN',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='VIN inválido (17 caracteres alfanuméricos, sin I, O, Q).', regex='^[A-HJ-NPR-Z0-9]{17}$')]),
        ),
    ]
