# Generated by Django 6.0.1 on 2026-04-13 22:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0011_stock_matricula_stock_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='Carrocería',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='Fecha_matriculación',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='Puertas',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AddField(
            model_name='stock',
            name='Tracción',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='Versión',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
