# Generated by Django 6.0.1 on 2026-04-13 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0012_stock_carrocería_stock_fecha_matriculación_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_photos/gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Web.stock')),
            ],
        ),
    ]
