# Generated by Django 6.0.1 on 2026-04-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0013_stockimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockimage',
            options={'ordering': ['orden', 'id']},
        ),
        migrations.AddField(
            model_name='stockimage',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
