# Generated by Django 6.0.1 on 2026-04-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0016_testdriverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdriverequest',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
