# Generated by Django 6.0.1 on 2026-04-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0017_testdriverequest_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdriverequest',
            name='preferred_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
